### ISSUE TITLE
some needs 

### ISSUE THREAD

**Issue by AbdelrahmanSayed155** [dynamsoft-dwt/dwt-react-advanced#1]
Good Job thanks Sir 
i need to hold byte stream because we havn't custom backend  so i need to hold byte stream from java script file  
thanks sir

**Comment by Tom-Dynamsoft** [comment]
Hi @AbdelrahmanSayed155 , I believe what you are looking for is this API ConvertToBlob. Check out https://www.dynamsoft.com/docs/dwt/API/Encode-Decode.html#ConvertToBlob
